image: python:3.9

stages:
  - lint
  - test
  - deploy

cache:
  paths:
    - .cache/pip

lint-job:
  stage: lint
  script:
    - pip install flake8
    - flake8 app.py

test-job:
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m pytest test_app.py
  artifacts:
    paths:
      - test-results.txt

deploy-job:
  stage: deploy
  script:
    - echo "Deploying to staging..."
  when: manual
